## datasource
datasource:
  name: test
  url: jdbc:mysql://10.11.100.58:3306/cloud2.4.4.2.0.0?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  username: root
  password: 706706

## Redis
spring:
  redis:
      host: ${redis.host}
      password: ${redis.password}
      port: ${redis.port}
      database: ${redis.database}
      # 连接超时时间（毫秒）
      timeout: 30000
      pool:
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

## Jwt 配置说明
safelogin:
  url:
    patterns: /api/v1/*
    exclude-patterns: /api/v1/login/*,/swagger-ui.html
    #    patterns: /**
    #    exclude-patterns: /api/v1/login/*,/swagger-resources/**,/v2/**,/swagger-ui.html
  #login页
  login:
    url: http://localhost:8080/api/v1/login